##################################################################
#               Custom Falco config file example                 #
#                                                                #
#  For more information about the configuraiton please refer to  #
#  https://falco.org/docs/reference/daemon/config-options/       #
#                                                                #
#  It is recommended to not directly modify this file. Instead   #
#  create a new config file under /etc/falco/config.override.d   #
#  to override existing keys or add new keys.                    #
#                                                                #
##################################################################

rules_files:
  - /etc/falco/rules.d

engine:
  modern_ebpf:
    cpus_for_each_buffer: 2
    buf_size_preset: 4
    drop_failed_exit: false

capture:
  enabled: false
  path_prefix: /tmp/falco
  mode: rules
  default_duration: 5000

plugins_hostinfo: true
